### ISSUE TITLE
Team desires - Misc Improvements

### ISSUE THREAD

**Issue by russelldutton** [301-Redirection/301-Project#150]
# TODO
- [x] Delete compound condition button
- [x] Easier to read triggers
- [x] Validation for each trigger
- [x] Edit styling for logical operator drop-downs in conditions

**Comment by russelldutton** [comment]
I've opted to go with Angular Material for the drop-downs and sliders for a more modern look and the fact that they're programmatically customisable

**Comment by vector67** [comment]
Fixed by #154
